In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from math import sqrt

In [2]:
df=pd.read_csv("data.csv")

In [15]:
df1=df.iloc[:,1:6]# Etiket ve tarih alınmadı
df1.head()

shown  clicked  converted  avg_cost_per_click  total_revenue
0  65877     2339         43                0.90         641.62
1  65100     2498         38                0.94         756.37
2  70658     2313         49                0.86         970.90
3  69809     2833         51                1.01         907.39
4  68186     2696         41                1.00         879.45

In [18]:
k = 3
max_iter = 100
threshold = 0.5
centroids = {} 

In [17]:
def distance(feat_one, feat_two):
    squared_distance = 0

    for i in range(len(feat_one)):
        squared_distance += (feat_one[i] - feat_two[i])**2

    return sqrt(squared_distance);

In [35]:
X=df1.values.tolist() 
len(X)

2115

In [43]:
for feature in X:
    distances = [distance(feature, centroids[centroid]) for centroid in centroids]
feature

[77907.0, 1391.0, 34.0, 0.99, 409.3]

In [54]:
classes.keys()

dict_keys([0, 1, 2])

In [57]:
centroids[2]

array([1.43267944e+05, 5.43615444e+03, 1.88459459e+02, 1.12308880e+00,
       2.94497591e+03])

In [59]:
centroid_points[1]

[array([6.68863710e+04, 1.17145161e+03, 3.08387097e+01, 6.76935484e-01,
        4.64046935e+02]),
 array([3.33482209e+04, 1.59505688e+03, 6.22679308e+01, 1.43488871e+00,
        9.60581286e+02]),
 array([1.18875981e+05, 5.30496310e+03, 2.26198810e+02, 1.33689286e+00,
        3.53003415e+03])]

In [49]:
for i in range(k):
    centroids[i] = X[i]

centroid_points = []
centroid_points.append([centroids[i] for i in range(k)])

errors = []

for epoch in range(max_iter):
    classes = {}
    for i in range(k):
        classes[i] = [] #K clusters initialization

    #Clustering the points based on distance function to centroids
    for feature in X:
        distances = [distance(feature, centroids[centroid]) for centroid in centroids]
        classification = distances.index(min(distances))
        classes[classification].append(feature)

    error = 0
    
    #Cost(J) calculation (intra-cluster distances)
    for j in classes.keys():
        for point in classes[j]:
            diff = distance(point, centroids[j])
            error += diff * diff 
    
    errors.append(error)
    
    #Terminate
    if epoch > 0:
        if (errors[epoch - 1] - error) < threshold:
            break

    #Recalculation of centroids
    for classification in classes:
        centroids[classification] = np.average(classes[classification], axis = 0)

    centroid_points.append([centroids[i] for i in range(3)])

In [25]:
print(centroid_points[-1])

[array([6.82766667e+04, 3.58947898e+03, 1.78216216e+02, 1.35717718e+00,
       2.80588096e+03]), array([2.66048507e+04, 1.35024919e+03, 5.49258861e+01, 1.52506982e+00,
       8.21665371e+02]), array([1.43267944e+05, 5.43615444e+03, 1.88459459e+02, 1.12308880e+00,
       2.94497591e+03])]
